create or replace PACKAGE     ut3.test_package_da_testare IS

   /* generated by utPLSQL for SQL Developer on 2019-10-01 16:58:27 */

   --%suite(test_package_da_testare)
   --%suitepath(alltests)

   --%test
   PROCEDURE moltiplica;

END test_package_da_testare;
/
create or replace PACKAGE BODY         ut3.test_package_da_testare IS

   /* generated by utPLSQL for SQL Developer on 2019-10-01 16:58:27 */

   --
   -- test moltiplica case 1: ...
   --
   PROCEDURE moltiplica IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      package_da_testare.moltiplica(1,2,l_actual);

      -- populate expected
      l_expected := 23;

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END moltiplica;

END test_package_da_testare;
/
